global:
  dockerRegistry: ""

image:
  pullSecrets: ["harbor"]
  plugin:
    repository: ascend-mindxdl/device-plugin
    tag: 6.0.2.1
  exporter:
    repository: ascend-mindxdl/npu-exporter
    tag: v6.0.0-alpha


initContainers:
  repository: pingcap/busybox
  tag: 1.34.1

volcano:
  enabled: true
  scheduler:
    repository: ascend-mindxdl/volcano-scheduler
    tag: 6.0.2-v1.7.0
  controller:
    repository: ascend-mindxdl/volcano-controller
    tag: 6.0.2-v1.7.0
  noded:
    repository: ascend-mindxdl/noded
    tag: v6.0.RC2
  clusterd:
    repository: ascend-mindxdl/clusterd
    tag: v6.0.RC2

devicePlugin:
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 500Mi
      cpu: 500m
  logLevel: 0

exporter:
  resources:
    limits:
      cpu: 200m
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 500Mi
  
