apiVersion: v1
kind: ServiceAccount
metadata:
  name: ascend-device-plugin-sa-310p
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-node-ascend-device-plugin-role-310p
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "update", "watch", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "patch"]
  - apiGroups: [""]
    resources: ["nodes/status"]
    verbs: ["get", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-node-ascend-device-plugin-rolebinding-310p
subjects:
  - kind: ServiceAccount
    name: ascend-device-plugin-sa-310p
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: pods-node-ascend-device-plugin-role-310p
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ascend-device-plugin310p-daemonset
  namespace: kube-system
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: ascend-device-plugin-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        name: ascend-device-plugin-ds
    spec:
      {{- include "atlas-device-plgin.imagePullSecrets" . | nindent 6 }}
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: huawei.com/Ascend310P
          operator: Exists
          effect: NoSchedule
        - key: "device-plugin"
          operator: "Equal"
          value: "v2"
          effect: NoSchedule
      priorityClassName: "system-node-critical"
      # nodeSelector:
      #   viper.sensetime.com/node-npu: "True"
      serviceAccountName: ascend-device-plugin-sa-310p
      containers:
        - image: {{ include "atlas-device-plugin.fullimage" . }}
          name: device-plugin-ctr
          command: [ "/bin/bash", "-c", "--"]
          {{- if .Values.volcano.enabled }}
          args: [ "device-plugin -useAscendDocker=false --presetVirtualDevice=false -volcanoType=true  -logFile=/var/log/mindx-dl/devicePlugin/devicePlugin.log -logLevel={{ .Values.devicePlugin.logLevel }}" ]
          {{- else }}
          args: [ "device-plugin -useAscendDocker=false --presetVirtualDevice=true -volcanoType=false  -logFile=/var/log/mindx-dl/devicePlugin/devicePlugin.log -logLevel={{ .Values.devicePlugin.logLevel }}" ]
          {{- end }}
          resources:
            requests:
              memory: {{ .Values.devicePlugin.resources.requests.memory }}
              cpu: {{ .Values.devicePlugin.resources.requests.cpu }}
            limits:
              memory: {{ .Values.devicePlugin.resources.limits.memory }}
              cpu: {{ .Values.devicePlugin.resources.limits.cpu }}
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: pod-resource
              mountPath: /var/lib/kubelet/pod-resources
            - name: hiai-driver
              mountPath: /usr/local/Ascend/driver
            - name: log-path
              mountPath: /var/log/mindx-dl/devicePlugin
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: pod-resource
          hostPath:
            path: /var/lib/kubelet/pod-resources
        - name: hiai-driver
          hostPath:
            path: /usr/local/Ascend/driver
        - name: log-path
          hostPath:
            path: /var/log/mindx-dl/devicePlugin
            type: DirectoryOrCreate
        - name: tmp
          hostPath:
            path: /tmp

