name: Lint and Test Charts

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - '*'
env:
  VERSION: 5.0.1
  

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4
      - name: lint
        run: helm lint .
      
      - name: render
        run: helm template .

      - name: Set git commit SHA/branchname
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
          branchName=$(git symbolic-ref --short -q HEAD)
          echo "BRANCH_NAME=$branchName" >> $GITHUB_ENV

      - name: package
        # todo: Publish
        run: helm package --version=$VERSION-$BRANCH_NAME-$COMMIT_SHORT_SHA --app-version=$VERSION .
